# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"
locale: en_US
title: "Wahab Aftab"
description: "An explorer who likes to play with data"
url: "//wahabaftab.github.io"
# logo:  '/images/Sunpath_41_N-1.png' # eitplume_SOHO_Sun_mod.png # 
date_format: "%-d %B %Y" # "originally %B %-d, %Y" 
# read_time: false
words_per_minute: 200
mathjax: true

encoding: UTF-8


google_fonts:
  - name: "PT Sans Narrow"
    weights: "400,400i,700,700i"
  - name: "sans-serif"
    weights: "400,400i,700,700i"
    
# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 3
# paginate_path: /page:num/

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

# Search
search_full_content: false # can have performance implications for large sites

# Collections
collections:
  certifications:
    output: true
    permalink: /:collection/:path/
  consult:
    output: true
    permalink: /:collection/:path/
  diffract:
    output: true
    permalink: /:collection/:path/
  blogs:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false
  # Resource defaults
  - scope:
      path: "_certifications"
    values:
      layout: certification
      entries_layout: list
      comments: false
      share: false
  - scope:
      path: "_blogs"
    values:
      layout: collection
      entries_layout: list
      comments: false
      share: false
   # Post defaults

#   # Collab defaults
#   - scope:
#       path: "_collab"
#     values:
#       layout: collection
#       entries_layout: grid
#       comments: true
#       share: true
  # Consult defaults
  # Diffract defaults
#   - scope:
#       path: "_diffract"
#     values:
#       layout: collection
#       entries_layout: list
#       comments: true
#       share: true





skin: "/assets/css/skins/default.css"
